name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 1 * * *'  # Run daily at 1:30 AM UTC

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8
      with:
        # General settings
        days-before-stale: 30
        days-before-close: 7
        operations-per-run: 30

        # Issue settings
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs within 7 days.

          If this issue is still relevant and you would like to keep it open, please:
          - Add a comment explaining why this issue should remain open
          - Add the "keep-open" label to prevent automatic closure

          Thank you for your contributions to git-stat! 🎯

        close-issue-message: |
          This issue has been automatically closed due to inactivity.

          If you believe this issue is still relevant, please:
          - Reopen the issue with updated information
          - Reference this issue in a new issue with current details

          We appreciate your understanding and contributions! ✨

        # Pull request settings
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs within 7 days.

          If this pull request is still relevant and you would like to keep it open, please:
          - Rebase your branch against the latest main branch
          - Address any merge conflicts or review comments
          - Add a comment explaining the current status
          - Add the "keep-open" label to prevent automatic closure

          Thank you for your contribution to git-stat! 🚀

        close-pr-message: |
          This pull request has been automatically closed due to inactivity.

          If you would still like to contribute this change, please:
          - Rebase your branch against the latest main branch
          - Open a new pull request with updated code
          - Reference this PR in the new one for context

          We appreciate your contributions and look forward to future pull requests! 🙏

        # Labels
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'keep-open,pinned,security,bug,enhancement,good first issue,help wanted'
        exempt-pr-labels: 'keep-open,pinned,security,work-in-progress,wip'

        # Don't mark as stale if these labels are present
        exempt-all-issue-assignees: true
        exempt-all-pr-assignees: true

        # Custom behavior for different types
        any-of-labels: 'bug,enhancement,documentation,question,help wanted'

        # Remove stale label when issues/PRs are updated
        remove-stale-when-updated: true

        # Don't process draft PRs
        exempt-draft-pr: true

        # Additional settings
        ascending: true
        delete-branch: false
        start-date: '2024-01-01T00:00:00Z'  # Only process issues/PRs after this date
